import type { Metadata } from "next";
import "./globals.css";
import Header from "@/features/components/Header";
import Footer from "@/features/components/Footer";

export const metadata: Metadata = {
  title: "Golf Together TV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full h-full bg-tv_bg flex flex-col`}>
        <div className="w-full fixed z-50"><Header/></div>
        <div className="mt-20 w-full h-full">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
